"""fix status column from todos

Revision ID: ed6e5b879cb4
Revises: 567bd42fdc75
Create Date: 2021-03-01 22:40:40.505799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed6e5b879cb4'
down_revision = '567bd42fdc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'status',
               existing_type=postgresql.ENUM('OPEN', 'DONE', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'status',
               existing_type=postgresql.ENUM('OPEN', 'DONE', name='status'),
               nullable=False)
    # ### end Alembic commands ###
